on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    branches:
      - main

name: Test
jobs:
  test_ios:
    name: Test iOS
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Units
        env:
          # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#xcode
          XCODE_PATH: "/Applications/Xcode_12.5.app"
        run: |
          sudo xcode-select -s ${{ env.XCODE_PATH }}
          xcrun simctl boot "iPhone 11"
          set -o pipefail \
          && xcodebuild test -scheme MarkdownKit -destination 'platform=iOS Simulator,OS=13.5,name=iPhone 11' \
          | xcpretty
  test_macos:
    name: Test macOS
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Units
        env:
          # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#xcode
          XCODE_PATH: "/Applications/Xcode_12.5.app"
        run: |
          sudo xcode-select -s ${{ env.XCODE_PATH }}
          set -o pipefail \
          && xcodebuild test -scheme MarkdownKit -destination 'platform=macOS' | xcpretty
