on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    branches:
      - main

name: Test
jobs:
  test:
    name: Units
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: Units
        env:
          # https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md#xcode
          XCODE_PATH: "/Applications/Xcode_11.5.app"
        run: |
          sudo xcode-select -s ${{ env.XCODE_PATH }}
          xcrun simctl boot "iPhone 11"
          set -o pipefail \
          && env NSUnbufferedIO=YES xcodebuild
            -scheme MarkdownKit \
            -destination 'platform=iOS Simulator,name=iPhone 11'
            -maximum-concurrent-test-simulator-destinations 2 \
            -jobs 2 \
            -parallelizeTargets \
            -parallel-testing-enabled YES \
            -parallel-testing-worker-count 2 \
            COMPILER_INDEX_STORE_ENABLE=NO \
            build-for-testing test-without-building \
          | xcpretty
