on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    branches:
      - main

name: Test
jobs:
  test_ios:
    name: Test iOS
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_12.5.app
      - name: Units
        run: |
          xcrun simctl boot "iPhone 11"
          set -o pipefail \
          && xcodebuild test -scheme MarkdownKit -destination 'platform=iOS Simulator,OS=13.5,name=iPhone 11' \
          | xcpretty
  test_macos:
    name: Test macOS
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_12.5.app
      - name: Units
        run: |
          set -o pipefail \
          && xcodebuild test -scheme MarkdownKit -destination 'platform=macOS' | xcpretty
